apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      telegram_api_url: "https://api.telegram.org"
    route:
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      receiver: "telegram"
      routes:
        - receiver: "telegram"
          group_wait: 10s
          match_re:
            severity: critical|warning
          continue: true
    receivers:
     - name: "telegram"
       telegram_configs:
       - send_resolved: true
         api_url: https://api.telegram.org
         bot_token: bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs
         chat_id: -1001763459775
         message: "Все пропало! Расходимся!\n{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: alertmanager
    meta.helm.sh/release-namespace: std-017-003
  creationTimestamp: "2023-09-07T10:40:08Z"
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
  name: alertmanager
  namespace: std-017-003
  resourceVersion: "1017927690"
  uid: db99229f-6762-4984-9cab-4ef7773df886