apiVersion: v1
data:
  sausage-store.yaml: |
    ---
    groups:
      - name: Sausage store rules
        rules:
        - alert: InstanceDown
          expr: up{app="backend"} == 0
          for: 1m
          labels:
            severity: critical
            project: "sausage_store"
            component: "Backend"
          annotations:
            summary: "Приложение недоступно {{ $labels.instance }}"
            description: "{{ $labels.instance }} недоступно более 1 минуты (current value: {{ $value }}s)"
        - alert: 500errors
          expr: sum(http_server_requests_seconds_count{status="500"})
          for: 1m
          labels:
            severity: critical
            project: "sausage_store"
            component: "Backend"
          annotations:
            description: "Зафиксированы ошибки 500 за последнюю минуту (current value: {{ $value }}s)"
        - alert: Latency
          expr: quantile(0.95,http_server_requests_seconds_max{uri="/api/orders", method="POST"}) >=0.1
          for: 5m
          labels:
            severity: moderate
            project: "sausage_store"
            component: "Backend"
        - alert: ActuatorError
          expr: http_server_requests_seconds_count{uri="/actuator/prometheus", status=~"4.."}
          for: 2m
          labels:
            severity: moderate
            project: "sausage_store"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: std-017-003
  creationTimestamp: "2023-09-06T05:33:15Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
  name: prometheus-rules
  namespace: std-017-003
  resourceVersion: "1015026979"
  uid: c8e85061-dcb2-4251-a82b-8255a8769a7c