stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.24.16
  environment:
    name: k8s
    url: https://zimin-nikolay-13.k8s.praktikum-services.tech
  when: manual
  before_script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$KUBE_CONFIG" > ~/.kube/config
    - chmod 644 ~/.kube/config
  script:
    - kubectl apply -f kubernetes/backend
    - kubectl apply -f kubernetes/backend-report
    - kubectl apply -f kubernetes/frontend
  after_script:
    - rm ~/.kube/config
  only:
    changes:
      - kubernetes/**/*