---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.frontend.replicasCount }}
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      nodeSelector:
        app: frontend
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ .Values.frontend.name }}
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: sausagestore-configmap
      imagePullSecrets:
        - name: docker-config-secret