---
apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.frontend.name }}
   labels:
     app: {{ .Values.frontend.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.frontend.name }}