---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendReport.name }}
  labels:
    app: {{ .Values.backendReport.name }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.backendReport.replicasCount }}
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.backendReport.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendReport.name }}
    spec:
      containers:
        - name: backend-report
          image: {{ .Values.backendReport.image }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: {{ .Values.backendReport.memoryLimits }}
            requests:
              cpu: {{ .Values.backendReport.cpuRequests }}
              memory: {{ .Values.backendReport.memoryRequests }}
          env:
            - name: PORT
              value: "8081"
            - name: DB
              value: {{ .Values.backendReport.mongoURI }}
          ports:
            - name: {{ .Values.backendReport.name }}
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
