---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: mongo
data:
  dns: bW9uZ29kYjovL3N0ZC0wMTctMDAzOlRlc3R1c3IxMjM0QHJjMWMtYmlmeDdiYmUzZGQ5Y2k2MC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTctMDAzP3Rsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVlCg==
type: Opaque
