---
apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.backendReport.name }}
   labels:
     app: {{ .Values.backendReport.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: {{ .Values.backendReport.name }}