# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpTFdOcExYUnZhMlZ1T2xvNFRqTkVRblY1Wm1ocVZURmpZbVZxY3pkRSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson