# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi0zMjUiLAogICAgICAgICAgICAicGFzc3dvcmQiOiI3bk5Mb1FYeVRGS0JXMll6SEpfeSIsCiAgICAgICAgICAgICJhdXRoIjoiWjJsMGJHRmlLMlJsY0d4dmVTMTBiMnRsYmkwek1qVTZOMjVPVEc5UldIbFVSa3RDVnpKWmVraEtYM2s9IgogICAgCX0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson