---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMHpNalU2TjI1T1RHOVJXSGxVUmt0Q1Z6Slpla2hLWDNrPSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: mongo
data:
  stringData: mongodb://:@rc1a-u0nwp06gbwh8qsoq.mdb.yandexcloud.net:27018/?tls=true&tlsAllowInvalidCertificates=true
type: Opaque
